"""empty message

Revision ID: 1759f2726262
Revises: 86b4bb7ed00b
Create Date: 2022-02-24 17:48:48.935801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1759f2726262'
down_revision = '86b4bb7ed00b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('created_utc', sa.Integer(), nullable=True))
    op.add_column('entries', sa.Column('signed_utc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'signed_utc')
    op.drop_column('entries', 'created_utc')
    # ### end Alembic commands ###
