"""empty message

Revision ID: 27159b29417b
Revises: 7668956155d0
Create Date: 2022-04-15 15:13:49.607495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27159b29417b'
down_revision = '7668956155d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_agencies_country_code'), 'agencies', ['country_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agencies_country_code'), table_name='agencies')
    # ### end Alembic commands ###
