"""empty message

Revision ID: 286444147b98
Revises: 27159b29417b
Create Date: 2022-04-15 16:02:10.227633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '286444147b98'
down_revision = '27159b29417b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('signing_sha256', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'signing_sha256')
    # ### end Alembic commands ###
