"""empty message

Revision ID: 2a94ded93de1
Revises: e3969ef086b1
Create Date: 2022-03-22 09:36:12.403167

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a94ded93de1'
down_revision = 'e3969ef086b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('edited_utc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'edited_utc')
    # ### end Alembic commands ###
