"""empty message

Revision ID: 3c5210b2f869
Revises: 1759f2726262
Create Date: 2022-03-05 10:32:38.373247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5210b2f869'
down_revision = '1759f2726262'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('police_users', sa.Column('banned_utc', sa.Integer(), nullable=True))
    op.add_column('victim_users', sa.Column('banned_utc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('victim_users', 'banned_utc')
    op.drop_column('police_users', 'banned_utc')
    # ### end Alembic commands ###
