"""empty message

Revision ID: 6d9e00f029f1
Revises: 2a94ded93de1
Create Date: 2022-03-23 16:01:37.264910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9e00f029f1'
down_revision = '2a94ded93de1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('created_ip', sa.String(length=16), nullable=True))
    op.add_column('entries', sa.Column('edited_ip', sa.String(length=16), nullable=True))
    op.add_column('entries', sa.Column('signed_ip', sa.String(length=16), nullable=True))
    op.add_column('entries', sa.Column('created_country', sa.String(length=2), nullable=True))
    op.add_column('entries', sa.Column('edited_country', sa.String(length=2), nullable=True))
    op.add_column('entries', sa.Column('signed_country', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'signed_country')
    op.drop_column('entries', 'edited_country')
    op.drop_column('entries', 'created_country')
    op.drop_column('entries', 'signed_ip')
    op.drop_column('entries', 'edited_ip')
    op.drop_column('entries', 'created_ip')
    # ### end Alembic commands ###
