"""empty message

Revision ID: 6e3b2ce4c452
Revises: b4de191c9bf5
Create Date: 2022-05-31 11:37:47.921137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e3b2ce4c452'
down_revision = 'b4de191c9bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_raw', sa.String(length=8192), nullable=True),
    sa.Column('text_html', sa.String(length=16384), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blogs')
    # ### end Alembic commands ###
