"""empty message

Revision ID: 7668956155d0
Revises: cb3f141cedf7
Create Date: 2022-04-04 14:28:13.532437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7668956155d0'
down_revision = 'cb3f141cedf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locker_shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agency_id', sa.Integer(), nullable=True),
    sa.Column('victim_id', sa.Integer(), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['agency_id'], ['agencies.id'], ),
    sa.ForeignKeyConstraint(['victim_id'], ['victim_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locker_shares')
    # ### end Alembic commands ###
