"""empty message

Revision ID: 9899320eae75
Revises: 6d9e00f029f1
Create Date: 2022-03-28 10:19:16.641447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9899320eae75'
down_revision = '6d9e00f029f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agencies', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.drop_column('agencies', 'country')
    op.add_column('victim_users', sa.Column('country_code', sa.String(length=2), nullable=True))
    op.drop_column('victim_users', 'country')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('victim_users', sa.Column('country', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_column('victim_users', 'country_code')
    op.add_column('agencies', sa.Column('country', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    op.drop_column('agencies', 'country_code')
    # ### end Alembic commands ###
