"""empty message

Revision ID: 99f92de65f36
Revises: 8445d5b4fff7
Create Date: 2022-02-22 14:01:00.476301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99f92de65f36'
down_revision = '8445d5b4fff7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('victim_users', sa.Column('username', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('victim_users', 'username')
    # ### end Alembic commands ###
