"""empty message

Revision ID: 9eb2d755a8a1
Revises: dd73739f31c4
Create Date: 2022-07-14 08:51:44.929379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9eb2d755a8a1'
down_revision = 'dd73739f31c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('victim_users', sa.Column('public_link_nonce', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('victim_users', 'public_link_nonce')
    # ### end Alembic commands ###
