"""empty message

Revision ID: a656d79f64b3
Revises: d97a273601f3
Create Date: 2022-02-23 08:40:33.289941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a656d79f64b3'
down_revision = 'd97a273601f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('agencies')
    # ### end Alembic commands ###
