"""empty message

Revision ID: b4de191c9bf5
Revises: 4cc92e5c46a2
Create Date: 2022-04-26 09:53:20.249720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4de191c9bf5'
down_revision = '4cc92e5c46a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('last_otp_code', sa.String(length=6), nullable=True))
    op.add_column('police_users', sa.Column('last_otp_code', sa.String(length=6), nullable=True))
    op.add_column('victim_users', sa.Column('last_otp_code', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('victim_users', 'last_otp_code')
    op.drop_column('police_users', 'last_otp_code')
    op.drop_column('admin_users', 'last_otp_code')
    # ### end Alembic commands ###
