"""empty message

Revision ID: ca77dcc3d5ff
Revises: dd5cf7565d7f
Create Date: 2022-03-07 21:28:31.977456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca77dcc3d5ff'
down_revision = 'dd5cf7565d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'admin_users', ['username'])
    op.create_unique_constraint(None, 'admin_users', ['email'])
    op.create_unique_constraint(None, 'agencies', ['name'])
    op.create_unique_constraint(None, 'police_users', ['email'])
    op.drop_column('police_users', 'username')
    op.create_unique_constraint(None, 'victim_users', ['email'])
    op.create_unique_constraint(None, 'victim_users', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'victim_users', type_='unique')
    op.drop_constraint(None, 'victim_users', type_='unique')
    op.add_column('police_users', sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'police_users', type_='unique')
    op.drop_constraint(None, 'agencies', type_='unique')
    op.drop_constraint(None, 'admin_users', type_='unique')
    op.drop_constraint(None, 'admin_users', type_='unique')
    # ### end Alembic commands ###
