"""empty message

Revision ID: cb3f141cedf7
Revises: 9899320eae75
Create Date: 2022-03-28 16:01:21.005765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb3f141cedf7'
down_revision = '9899320eae75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('victim_users', sa.Column('allow_leo_sharing', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('victim_users', 'allow_leo_sharing')
    # ### end Alembic commands ###
