"""empty message

Revision ID: d97a273601f3
Revises: 99f92de65f36
Create Date: 2022-02-22 14:15:22.531487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd97a273601f3'
down_revision = '99f92de65f36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_raw', sa.String(length=8192), nullable=True),
    sa.Column('text_html', sa.String(length=16384), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('police_users', sa.Column('username', sa.String(length=64), nullable=True))
    op.add_column('police_users', sa.Column('created_utc', sa.Integer(), nullable=True))
    op.add_column('police_users', sa.Column('pw_hash', sa.String(length=256), nullable=True))
    op.add_column('police_users', sa.Column('otp_secret', sa.String(length=32), nullable=True))
    op.add_column('police_users', sa.Column('email', sa.String(length=256), nullable=True))
    op.add_column('victim_users', sa.Column('email', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('victim_users', 'email')
    op.drop_column('police_users', 'email')
    op.drop_column('police_users', 'otp_secret')
    op.drop_column('police_users', 'pw_hash')
    op.drop_column('police_users', 'created_utc')
    op.drop_column('police_users', 'username')
    op.drop_table('entries')
    # ### end Alembic commands ###
