"""empty message

Revision ID: dd5cf7565d7f
Revises: fd3af1622242
Create Date: 2022-03-07 16:49:41.701282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd5cf7565d7f'
down_revision = 'fd3af1622242'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_users', sa.Column('login_nonce', sa.Integer(), nullable=True))
    op.add_column('police_users', sa.Column('login_nonce', sa.Integer(), nullable=True))
    op.add_column('victim_users', sa.Column('login_nonce', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('victim_users', 'login_nonce')
    op.drop_column('police_users', 'login_nonce')
    op.drop_column('admin_users', 'login_nonce')
    # ### end Alembic commands ###
