"""empty message

Revision ID: dd73739f31c4
Revises: 21af444aa272
Create Date: 2022-06-20 15:16:00.209048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd73739f31c4'
down_revision = '21af444aa272'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'blogs', 'admin_users', ['author_id'], ['id'])
    op.add_column('entries', sa.Column('image_sha256', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entries', 'image_sha256')
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    # ### end Alembic commands ###
