"""empty message

Revision ID: e3969ef086b1
Revises: ca77dcc3d5ff
Create Date: 2022-03-10 15:33:12.436652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3969ef086b1'
down_revision = 'ca77dcc3d5ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bad_domains',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.add_column('agencies', sa.Column('city', sa.String(length=128), nullable=True))
    op.add_column('agencies', sa.Column('state', sa.String(length=128), nullable=True))
    op.create_unique_constraint(None, 'agencies', ['domain'])
    op.add_column('police_users', sa.Column('ban_reason', sa.String(length=128), nullable=True))
    op.add_column('victim_users', sa.Column('ban_reason', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('victim_users', 'ban_reason')
    op.drop_column('police_users', 'ban_reason')
    op.drop_constraint(None, 'agencies', type_='unique')
    op.drop_column('agencies', 'state')
    op.drop_column('agencies', 'city')
    op.drop_table('bad_domains')
    # ### end Alembic commands ###
