"""empty message

Revision ID: e3f6117afea0
Revises: 3c5210b2f869
Create Date: 2022-03-05 12:37:49.269904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f6117afea0'
down_revision = '3c5210b2f869'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('created_utc', sa.Integer(), nullable=True),
    sa.Column('pw_hash', sa.String(length=256), nullable=True),
    sa.Column('otp_secret', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('banned_utc', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('entries', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'entries', 'victim_users', ['author_id'], ['id'])
    op.add_column('police_users', sa.Column('last_verified_utc', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('police_users', 'last_verified_utc')
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_column('entries', 'author_id')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
