"""empty message

Revision ID: fd3af1622242
Revises: e3f6117afea0
Create Date: 2022-03-07 16:47:35.056458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd3af1622242'
down_revision = 'e3f6117afea0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('victim_users', sa.Column('created_country', sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('victim_users', 'created_country')
    # ### end Alembic commands ###
